import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/nav/Navbar";
import { tiroBangla } from "@/components/ui/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="bn" className={cn("h-full", "antialiased")}>
      <body className={tiroBangla.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
